server:
  port: 8081

spring:
  application:
    name: fraud
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    format_sql: true
  datasource:
    platform: postgres
    url: jdbc:postgresql://localhost:5432/fraud
    username: ibetar
    password: password
    driverClassName: org.postgresql.Driver

eureka:
  client:
    service-url:
      defaultZOne: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true