server:
  port: 8081
spring:
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: create-drop
  datasource:
    platform: postgres
    url: jdbc:postgresql://localhost:5432/fraud
    username: ibetar
    password: password
    driverClassName: org.postgresql.Driver
